### PR TITLE
Custom class names and counter based namespacing

### LINKED ISSUE #5: Avoid duplicate css class names by replacing Math.random()
Suggest replacing Math.random() with a perfect 32bit hash function to avoid collisions which could cause duplicate css class names

## [Robert Jenkins' 32 bit integer hash function](https://gist.github.com/badboy/6267743)

```js
import stylis from './stylis.js'

const cache = {}
let seed = 0;  // or Math.random() * 4294967295;
const p = new Uint32Array(1);
const hash = () => {
  //Math.random()
  p[0] = seed++;
  p[0] = (p[0]+0x7ed55d16) + (p[0]<<12);
  p[0] = (p[0]^0xc761c23c) ^ (p[0]>>19);
  p[0] = (p[0]+0x165667b1) + (p[0]<<5);
  p[0] = (p[0]+0xd3a2646c) ^ (p[0]<<9);
  p[0] = (p[0]+0xfd7046c5) + (p[0]<<3);
  p[0] = (p[0]^0xb55a4f09) ^ (p[0]>>16);
  return p[0].toString(16);
}

const sheet = document.createElement('style')
document.head.appendChild(sheet)
```

## Math.random() vs 32bit Hash function performance
https://jsbench.me/
### Using cache with Math.random() to prevent collision
const cache = {
    abc123: true,
    def123: true,
    aba123: true,
    bab123: true,
    bcb123: true,
    cdc123: true,
    dde123: true,
}
const hash = Math.random().toString(36).replace('0.', '')
cache[hash]
844,675 ops/s ±2.41%
65.03% slower

### Using 32bit hash function
let seed = 0;  // or Math.random() * 4294967295;
const p = new Uint32Array(1);  
p[0] = seed++;
  p[0] = (p[0]+0x7ed55d16) + (p[0]<<12);
  p[0] = (p[0]^0xc761c23c) ^ (p[0]>>19);
  p[0] = (p[0]+0x165667b1) + (p[0]<<5);
  p[0] = (p[0]+0xd3a2646c) ^ (p[0]<<9);
  p[0] = (p[0]+0xfd7046c5) + (p[0]<<3);
  p[0] = (p[0]^0xb55a4f09) ^ (p[0]>>16);
  p[0].toString(16);

2,415,448 ops/s ±0.52%
fastest

### LINKED ISSUE #6: Worth adding custom class names?
Do you think adding custom css class name support is worth it from a debugging perspective?

Example:
.my-class-name-af28f1eb
.another-class-name-e3fd91bc
instead of
.csz-af28f1eb
.csz-e3fd91bc

I'm not sure how you would support this since your css function call uses a template string.
css('background: blue', 'my-class-name')

### PR DESCRIPTION
**Pull request by B-Teague**
closes #5 
closes #6 

Added support for custom css class names.
Default class name is .csz-# where # is a counter.

No more collisions. Faster. Easier to debug.

### CODE REVIEW

**Comment by lukejacksonn** [comment]
Hey man 👋 I have taken a look at this and as much as it might improve on a few things. It takes away somewhat from the simplicity, which is a quality I really strive for. My issue here really is:

- I have never experienced a name collision
- I have never found it slow
- I have not struggled to debug

Although I appreciate you are accounting for these issues that _might_ arise; I wonder if anyone else has experienced any of these things, and if not then is this early optimisation?

**Comment by B-Teague** [comment]
Is it more simple to generate a hash function or increment a counter?

Even if you personally never experience a collision, does the risk of a collision increase as more and more people like and use your library?

Debugging was just one example I could think of where custom names might be helpful.  Can you think of a different reason why you or someone else might enjoy having explicit names instead of implicit generated names?

I absolutely love this library and can definitely appreciate the phrase, “simple is better.”  I worked hard on the pull request, and I love the idea of having explicit class names that are visible for users.

**Comment by B-Teague** [comment]
Whew!  I managed to reduce the original code from 38 to 35 lines while adding the custom class name feature.

**Comment by lukejacksonn** [comment]
Well done @B-Teague 😅 it is not that I didn't think your code was good or anything.. my decision not to merge this was solely down to a "if it ain't broke don't fix it" mentality.

If people come with debugability or collision issues then I will call on you for this code!

**Pull request closed without merging**
